### ISSUE TITLE
Cannot use mod (It's updated to 1.18 version)

### ISSUE THREAD

**Issue by 3gData** [Coderx-Gamer/shulker-dupe#6]
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Shulker Dupe' (shulker-dupe) 1.0.0 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Shulker Dupe' (shulker-dupe) 1.0.0 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 3 more
****

**Comment by GiveMeFox** [comment]
Install fabric, any version.

**Comment by GiveMeFox** [comment]
its said in the error

**Comment by Coderx-Gamer** [comment]
u dont have fabric installed correctly

**Comment by Coderx-Gamer** [comment]
try reinstalling it
